modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Uraneptus/Sullys-Mod/issues"

[[mods]] #mandatory
modId = "glowworms" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "sullysmod_banner.png" #optional
authors = "Uraneptus" #optional
credits = "Assets by GoesBySully" #optional
displayURL = "https://github.com/Uraneptus/Glowworms"
displayName = "Glowworms" #mandatory
description = '''
'''
displayTest = "MATCH_VERSION"

[[dependencies.glowworms]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.glowworms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[modproperties.sullysmod]
    catalogueImageIcon = "sullysmod_icon.png"
    #configuredBackground = "sullysmod:textures/block/polished_jade_bricks.png"